#!/bin/bash

showHelp() {
echo "
OPTIONS:
  -l   Send commands only on newline (enter key). By default, each character is sent immediately.
  -h   Show this help.
"
}

queueFile="$(ls -t ~/.tunewich/tmp/tunewich*-command-queue | head -1)"
commitMode=char

while getopts l flag; do
  case $flag in
    l) commitMode=line;;
    h) showHelp; exit 0;;
  esac
done
[[ $OPTIND -gt 1 ]] && shift $((OPTIND - 1))

[[ -z "$queueFile" ]] && {
	echo "No command queue file found"
	exit 2
}

if [[ -n "$@" ]]; then
	echo "$@" > "$queueFile" &
elif [[ ! -t 1 || -p /dev/stdin ]]; then
	cat /dev/stdin > "$queueFile"
	echo > "$queueFile" # newline for safety
else
	echo "Beginning interactive input"
	echo "Run 'tunewich --help' to see the list of interactive commands."
	echo "Note that most interactive commands won't work, like /eq, /bpm."
	echo "Mode: $commitMode"
	echo
	echo "Ctrl+C to exit."
	echo

	prompt='tunewich $ '
	inputLine=
	1>&2 echo -n "$prompt"
	while IFS= read -s -r -n1 ch; do
		case "$ch" in
			'')
				# surely other things will also come across as empty, besides newline?
        [[ $commitMode = line ]] && echo -e "$inputLine" > "$queueFile"
				inputLine=
				ch=$'\n'
				echo -ne "$ch";;
			"") inputLine=;;
			"") [[ ${#inputLine} -gt 0 ]] && inputLine="${inputLine:0:$((${#inputLine} - 1))}";;
			*) inputLine+="$ch";;
		esac
		1>&2 echo -ne "\r${prompt}${inputLine}"
		[[ $commitMode = char ]] && echo -ne "$ch" > "$queueFile"
	done
fi
