#!/usr/bin/env ruby

# TODO: catch C-t, or something like it, to pass interactive commands to the script

require "open-uri"
require "optparse"
require "json"

module Tunewich
	class Player
		def initialize
			@sessionID = Random.rand(1024)
			@scriptDir = File.dirname(__FILE__)
			@playlistName = nil
			@trackIndex = nil
			@tracks = []
			@libraryFilePath = "#{@scriptDir}/../library.json"
			@library = JSON.parse(File.read(@libraryFilePath))

			parseOptions

			if not @fileDirectory
				puts "please specify an input directory with -i"
				exit
			end

			if @tracks.length === 0
				if not @playlistName
					promptForPlaylist
				end

				usePlaylist @playlistName
				titleBlock "Playlist: #{@playlistName} (#{@tracks.length})", '#'
			else
				titleBlock "Playing #{@tracks.length} tracks", '#'
			end

			if @trackIndex == nil
				if @shuffle
					shuffleIndex()
				else
					@trackIndex = 0
				end
			elsif @trackIndex.to_i === 0
				@trackIndex = findTrackIndex @trackIndex
			else
				@trackIndex = @trackIndex.to_i - 1
			end

			# TODO: catch SIGINT (ctrl+c) & prompt for playlist again
			playbackSuccessful = true
			while playbackSuccessful do
				playbackSuccessful = play @tracks[@trackIndex]
				nextTrack()
			end
		end

		private

		def parseOptions
			parser = OptionParser.new

			parser.on("-t", "--track INDEX/QUERY", "If a number is given, seek to that track. If a string, the title of the track is searched for.") do |trackQuery|
				if trackQuery.to_i != 0
					@trackIndex = trackQuery.to_i - 1
				else
					@trackIndex = trackQuery
				end
			end
			parser.on("-a", "--all", "Play entire library.") do
				useEntireLibrary
			end
			parser.on("-p", "--playlist QUERY", "Partial or full name of a playlist.") do |playlistQuery|
				@playlistName = findPlaylistName playlistQuery
			end
			parser.on("-i", "--input-dir DIR", "Directory from which to read the playlist files.") do |inputDir|
				@fileDirectory = inputDir
			end
			parser.on("-r", "--rating MIN_RATING", "Only play tracks rated at least the minimum given.") do |rating|
				filterTracksByRating rating.to_i
			end
			parser.on("-d", "--enable-download", "Enable downloading files when encountering a playlist file without a cached file already download.") do
				@enableDownload = true
			end
			parser.on("-s", "--shuffle", "Enable shuffle.") do
				@shuffle = true
			end
			parser.on("-l", "--loop", "Loop, even if a track doesn't have an A/B loop defined.") do
				@loop = true
			end
			parser.on("-n", "--new-track YOUTUBE_ID", "Add a track to the playlist and save.") do |id|
				promptForPlaylist if not @playlistName
				getIdFromYoutubeUrl! id
				newTrack = createTrack id
				addTrackToPlaylist newTrack, @playlistName
				writeLibraryToFile
				exit
			end
			parser.on("-q", "--query QUERY", "Search YouTube for a video.") do |query|
				@tracks = searchYouTube query
			end
			parser.on("-h", "--help", "Show this help.") do
				puts parser.help()
				exit
			end

			@mplayerOverrideCommands = parser.parse(ARGV)
		end

		def promptForPlaylist
			puts "Please choose a playlist:\n  #{@library['playlists'].keys.join "\n  "}"
			selectedListName = nil
			while !selectedListName do
				selectedListName = findPlaylistName STDIN.gets.chomp
				if !selectedListName
					puts "No matches. Try again"
				end
			end

			@playlistName = selectedListName
		end

		def findTrackIndex(query)
			trackTitles = @tracks.map{|t| t['title']}
			findInList(query, trackTitles)[:index]
		end

		def findPlaylistName(query)
			findInList(query, @library['playlists'].keys)[:value]
		end

		def findInList(query, list)
			queryPattern = Regexp.new(query + '|' + query.gsub(/\s+/, '').split('').join('.*'), Regexp::IGNORECASE)
			matches = []
			list.each_with_index do |value, index|
				matchedPortion = queryPattern.match(value)
				if matchedPortion
					match = {
						:index => index,
						:value => value,
						:matchLength => matchedPortion[0].length
					};
					match[:density] = query.length.to_f / match[:matchLength].to_f
					match[:breadth] = match[:matchLength].to_f / match[:value].length.to_f
					match[:score] = (match[:breadth] + match[:density]) / 2
					matches.push(match)
				end
			end

			if matches.length === 0
				return false
			end

			matches.sort_by { |match| 1 - match[:score] } if matches.length > 1

			{:index => matches[0][:index], :value => matches[0][:value]}
		end

		def usePlaylist(name)
			@playlist = @library['playlists'][name]
			@tracks = []
			@playlist['tracks'].each do |trackReference|
				@tracks.push @library['library'][trackReference['id']]
			end
		end

		def useEntireLibrary
			@tracks = []
			@library['library'].keys.each do |trackKey|
				@tracks.push @library['library'][trackKey]
			end
		end

		def nextTrack
			if @shuffle
				shuffleIndex()
			else
				@trackIndex += 1
				@trackIndex %= @tracks.length
			end
		end

		def shuffleIndex
			@trackIndex = Random.rand(@tracks.length - 1)
		end

		def play(track)
			titleBlock "[#{@trackIndex + 1}] - #{@tracks[@trackIndex]['title']}"

			if not fileExistsFromID? track['src']
				if not @enableDownload
					streamName = 'youtube-stream'
					streamPath = mediaFilePath = makeStream streamName
				end

				if not downloadFromYouTubeID track['src'], streamPath
					return false
				end
			end

			mediaFilePath ||= findFile track['src']

			mplayerCommands = []

			# TODO: clean up these tests for streaming
			if track['loop'].kind_of?(Array)
				if !streamName
					duration = track['loop'][1] - track['loop'][0]

					mplayerInputFile = putInTempFile 'mplayer-input', "seek -999:00:00\n" # this is a silly way to do it. -100% doesn't work. Still, there's a moment of the audio heard before this command is run.
					mplayerCommands.push("-input file=#{mplayerInputFile}")

					# loop back from B to A
					mplayerCommands.push("-ss #{track['loop'][0]}")
					mplayerCommands.push("-endpos #{duration}")
				else
					titleBlock "This track has an A/B loop, but looping is not supported while streaming. Add the -d option to enable downloading."
				end
			end

			if !streamName
				mplayerCommands.push("-loop 0") if track['loop'] or @loop
			end

			mplayerCommands.push("-novideo")
			mplayerCommands += @mplayerOverrideCommands

			mplayerStatus = system "mplayer \"#{mediaFilePath}\" #{mplayerCommands.join ' '}"

			deleteStream streamName if streamName
			deleteTempFile 'mplayer-input'

			mplayerStatus
		end

		def findFile(id)
			`ls -1 #{getFilePrefixFromId id}*`.strip
		end

		def fileExistsFromID?(id)
			system "ls -1 #{getFilePrefixFromId id}*"
		end

		def getFilePrefixFromId(id)
			"#{@fileDirectory}/tunewich-#{id}"
		end

		def downloadFromYouTubeID(id, streamPath = nil)
			puts "Downloading file (#{id})"

			youtubeDlCommandBegin = "youtube-dl -f bestaudio"
			youtubeDlCommandEnd = "-- #{id}"

			if streamPath
				streamPid = spawn("#{youtubeDlCommandBegin} -o - #{youtubeDlCommandEnd} > \"#{streamPath}\"")
				Process.detach(streamPid)
				return true
			else
				result = system "#{youtubeDlCommandBegin} -o \"#{getFilePrefixFromId id}-%(title)s.%(ext)s\" #{youtubeDlCommandEnd}"
				if not result
					puts "Download interrupted..."
				end
			end

			result
		end

		def titleBlock(message, fill = '=', width = 80)
			blockRow = fill * width
			padding = '  '
			marginSize = (width - message.length) / 2 - padding.length
			marginLeft = marginSize > 1 ? fill * marginSize : ''
			marginRight = marginLeft
			if message.length % 2 == 1 then marginRight += fill end
			puts "\n#{blockRow}"
			puts "#{marginLeft}#{padding}#{message}#{padding}#{marginRight}"
			puts blockRow
		end

		def getTempFilePath(name)
			"/tmp/tunewich-#{@sessionID}-#{name}"
		end

		def putInTempFile(name, value)
			path = getTempFilePath name
			File.write(path, value)
			path
		end

		def putInTempFile(name, value)
			path = getTempFilePath name
			File.write(path, value)
			path
		end

		def deleteTempFile(name)
			path = getTempFilePath name
			if File.exists? path
				File.delete path
			end
		end

		def makeStream(name)
			path = getTempFilePath name
			if File.exists? path
				raise "The temp file '#{name}' already exists. (#{path})"
			end
			if not system "mkfifo \"#{path}\""
				raise "ERROR: Could not create the stream file (#{path})"
			end
			path
		end

		def getIdFromYoutubeUrl! url
			url.sub!(/^.*v=/, '')
		end

		def filterTracksByRating rating
			@tracks.keep_if { |track| track['rating'] && track['rating'] >= rating }
		end

		def createPlaylist name, tracks = [], description = ''
			newPlaylist = {
				'description' => description,
				'public' => true,
				'tracks' => tracks
			}
			@library['playlists'][name] = newPlaylist
		end

		def createTrack id, title = nil
			if not title
				puts "Fetching title for YouTube ID #{id}..."
				title = `youtube-dl --get-title -- #{id}`.chomp

				if title.empty?
					title = 'Unknown'
					puts "Video not found. Cannot get title."
				end
			end

			{
				'src' => id,
				'title' => title
			}
		end

		def addTrackToPlaylist track, playlistName
			trackReference = {
				'id' => track['src']
			}

			@library['library'][trackReference['id']] = track
			@library['playlists'][playlistName]['tracks'].push trackReference

			puts "Saved '#{track['title']}' (#{trackReference['id']}) to playlist '#{playlistName}'"
		end

		def writeLibraryToFile
			libraryJSON = JSON.pretty_generate(@library)
			File.write(@libraryFilePath, libraryJSON) if libraryJSON
		end

		def searchYouTube query, offset = 0, count = 20
			puts "Searching YouTube for '#{query}'"
			resultsPerPage = 20
			page = (offset.to_f / resultsPerPage.to_f).to_i + 1
			queryParameter = URI::encode(query)
			queryUrl="https://www.youtube.com/results?search_query=#{queryParameter}&page=#{page}"

			queryResultIds = []
			open(queryUrl) do |handle|
				html = []
				handle.each_line { |line| html.push(line) }
				queryResultIds = html.grep(/href="\/watch/).map! do |line|
					line.sub!(/^.*watch\?v=([^\"&<]+).*\n/, '\1')
				end
				queryResultIds.uniq!
			end

			resultTracks = []
			queryResultIds.slice(0, count).each_with_index do |id, index|
				resultTracks.push createTrack id, "Search '#{query}': (#{id})"
			end

			resultTracks
		end

		alias deleteStream deleteTempFile

	end
end

Tunewich::Player.new
