#!/bin/bash

queueFile="$(ls -t ~/.tunewich/tmp/*-tunewich-command-queue | head -1)"

[[ -z "$queueFile" ]] && {
	echo "No command queue file found"
	exit 2
}

if [[ -n "$@" ]]; then
	echo "$@" > "$queueFile" &
else
	echo "Beginning interactive input"
	echo "Run 'tunewich --help' to see the list of interactive commands."
	echo "Note that most interactive commands won't work, like /eq, /bpm."
	echo
	echo "Ctrl+C to exit."
	echo

	while true; do
		read -p "tunewich\$ "
		echo "$REPLY" > "$queueFile"
	done
fi
